baseURL = 'https://github.com/setup-armbian-for-tvbox/setup-armbian-for-tvbox.github.io/'
languageCode = 'pt-br'
title = 'setup-armbian-for-tvbox'
theme = [] # Mantemos vazio para usar o layout customizado abaixo
